<?php
namespace app\modules\admin;
/**
 * Created by PhpStorm.
 * User: jason
 * Date: 2016/9/26
 * Time: 14:49
 */
class Module extends \yii\base\Module
{

        public function init()
        {
            parent::init(); // TODO: Change the autogenerated stub
           // \Yii::configure($this, require(__DIR__ . '/config.php'));  加载改模块的配置文件
        }
}